name: Compile OS X
#on: [push]
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  LANG: "de_DE.UTF-8"

jobs:
  compile-jpackage:
    runs-on: macos-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@master

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Package
      run:  mvn package
      env: 
        LANG: en_EN

    - name: JPackage
      run:   mvn jpackage:jpackage@osx
      env: 
        LANG: en_EN
        
    - name: Show result JPackage
      continue-on-error: true
      run: ls target/jpackage
      
    - name: Upload
      continue-on-error: true
      uses: garygrossgarten/github-action-scp@release
      with:
        verbose: true
        local: target/jpackage/Commlink6-${{ env.RELEASE_VERSION }}.dmg
        remote: /var/www/html/commlink6-builds/osx/Commlink6-Updater-${{env.RELEASE_VERSION}}.dmg
        host: eden.rpgframework.de
        username: ghcommlink
        password: ${{ secrets.DEPLOY_PASSWORD }}
